### ISSUE TITLE
use @babel/runtime

### ISSUE THREAD

**Issue by afc163** [react-component/textarea#1]
可以降低打包体积。

https://github.com/react-component/tabs/commit/7b08d5e309553b3299e170d514ef19bca38138ff

发个 patch。

**Comment by Kermit-Xuan** [comment]
👌

**Comment by zombieJ** [comment]
@Kermit-Xuan Pls help to add `zombiej` & `afc163` as `rc-textarea` owner.

**Comment by Kermit-Xuan** [comment]
![image](https://user-images.githubusercontent.com/33770367/86003791-e32ad900-ba44-11ea-89e7-82414ab5bcfe.png)

**Comment by Kermit-Xuan** [comment]
是这样么？

**Comment by zombieJ** [comment]
嗯~~~

**Comment by Kermit-Xuan** [comment]
是出了什么问题？

**Comment by zombieJ** [comment]
https://github.com/react-component/textarea/commit/92fd5e99339cec6da43fdff6c474928860daf4df

**Comment by zombieJ** [comment]
npm 权限没更新，你帮我发一下吧 @Kermit-Xuan

**Comment by Kermit-Xuan** [comment]
我直接发了 0.2.5

**Comment by zombieJ** [comment]
https://github.com/react-component/textarea/pull/2  好了，这个应该就好了 @Kermit-Xuan

**Comment by zombieJ** [comment]
> npm 权限没更新，你帮我发一下吧 @Kermit-Xuan

好像还是没有同步出来，`npm owner add` 加一下试试~

**Comment by Kermit-Xuan** [comment]
加了你试试

**Comment by zombieJ** [comment]
有了，thx

**Comment by zombieJ** [comment]
我来发一下

**Comment by Kermit-Xuan** [comment]
非常不好意思，改完了后自己没有测试。

**Comment by Kermit-Xuan** [comment]
> 我来发一下

OK

**Comment by zombieJ** [comment]
别客气， 你用钉钉吗？加你一下到 antd 大开发者群~

**Comment by Kermit-Xuan** [comment]
kerm1t
