### ISSUE TITLE
Textarea blinks when the value is changed.

### ISSUE THREAD

**Issue by nieyuyao** [react-component/textarea#17]
### Reproduction link

https://codesandbox.io/s/focused-tu-hlr3h1?file=/App.jsx

### Steps to reproduce

When I change the value, the textarea flickers. It seemed like the height suddenly got bigger and then recovered.

**Comment by nieyuyao** [comment]
It seems that a issue in antd is also related to this. https://github.com/ant-design/ant-design/issues/35632

**Comment by nieyuyao** [comment]
This is because handleResize is asynchronous.
https://github.com/react-component/textarea/blob/12dc37f892557bf875dd53948d51a6b93f525511/src/ResizableTextArea.tsx#L56-L69
Textarea will not be set to a specific style, but the default when initializing.

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/textarea/pull/23

https://codesandbox.io/s/antd-reproduction-template-forked-wy5hw2
